dist: xenial

language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - |
    if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]; then
      pip install configparser
    fi

# command to run tests
script:
  - ./xlsx_inventory.py --config --file example.xlsx --hostname-col A --group-by-col B --sheet Sheet1
  - ./xlsx_inventory.py --list
